IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME = 'Tags' AND TABLE_SCHEMA = 'dbo'
)
BEGIN
	CREATE TABLE Tags (
		Id INT PRIMARY KEY,
		Name VARCHAR(20) NOT NULL
	)
END

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME = 'Statuses' AND TABLE_SCHEMA = 'dbo'
)
BEGIN
	CREATE TABLE Statuses (
		Id INT PRIMARY KEY,
		Name VARCHAR(20) NOT NULL
	)
END

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME = 'Tasks' AND TABLE_SCHEMA = 'dbo'
)
BEGIN
	CREATE TABLE Tasks (
		Id INT PRIMARY KEY,
		Title VARCHAR(50) NOT NULL,
		Note VARCHAR(200) NULL,
		CreatedOn DATETIME2 NOT NULL,
		ModifiedOn DATETIME2 NULL,
		CompletedOn DATETIME2 NULL,
		ExpectedCompletionDate DATETIME2 NOT NULL,
		StatusId INT NOT NULL,
		FOREIGN KEY(StatusId) REFERENCES Statuses(Id) ON DELETE NO ACTION
	)
END

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME = 'TaskTagMapping' AND TABLE_SCHEMA = 'dbo'
)
BEGIN
	CREATE TABLE TaskTagMapping (
		Id INT PRIMARY KEY,
		TaskId INT NOT NULL,
		TagId INT NOT NULL,
		FOREIGN KEY(TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE,
		FOREIGN KEY(TagId) REFERENCES Tags(Id) ON DELETE CASCADE
	)
END